services:
  - type: web
    name: powershell-server-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: powershell-server-api
          property: port
    autoDeploy: true
    branch: main